name: Build (with Tactical View)
on:
  workflow_dispatch:
    inputs:
      test:
        description: 'This is an option'
        type: boolean
        required: false
        default: false
jobs:
  Linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Hello 1
      run: echo hello world
    - name: Hello 2
      run: echo hello world
    - name: Hello 3
      run: echo hello world
