name: Build
on:
  push:
  workflow_dispatch:
jobs:
  Linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Hello
      run: echo hello world
    - name: Create artifact
      run: echo "linux-1" > linux-1.txt
    - name: Create artifact
      run: echo "linux-2" > linux-2.txt
    - name: Upload actifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: Linux
        path: |
          linux-1.txt
          linux-2.txt
  Android:
    runs-on: ubuntu-20.04
    steps:
    - name: Hello
      run: echo hello world
    - name: Create artifact
      run: echo "android-1" > android-1.txt
    - name: Create artifact
      run: echo "android-2" > android-2.txt
    - name: Upload actifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: Android
        path: |
          android-1.txt
          android-2.txt
  Release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [Linux, Android]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Get all build artifacts
        uses: actions/download-artifact@v4
      - name: List
        run: |
          find . -name '*' -print
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **
