name: Test
on:
  push:
  workflow_dispatch:
jobs:
  Linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Create an artifact
        run: |
          echo hello world > hello.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hello
          path: "*.txt"
  Release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-20.04
    needs: [Linux]
    permissions:
      contents: write
    steps:
      - name: Get all build artifacts
        uses: actions/download-artifact@master
        with:
          path: .
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **
