name: Test
on:
  push:
  workflow_dispatch:
Linux:
  runs-on: ubuntu-20.04
  steps:
    - name: Create an artifact
      run: |
        echo hello world > hello.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hello
        path: "*.txt"
