name: Build
on:
  push:
  workflow_dispatch:
jobs:
  Linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Hello
      run: echo hello world
    - name: Create artifact
      run: echo "hello world" > hello.txt
    - name: Create artifact
      run: echo "goodbye world" > goodbye.txt
    - name: Upload actifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: Hello
        path: |
          hello.txt
          goodbye.txt
  Release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [Linux]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Get all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            **
